image:
  repository: apachesuperset.docker.scarf.sh/apache/superset
  tag: "latest"
  pullPolicy: IfNotPresent

initImage:
  repository: apache/superset
  tag: dockerize
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

ingress:
  enabled: false

postgresql:
  enabled: false

secretEnv:
  create: false

envFromSecret: superset-env

redis:
  enabled: false

bootstrapScript: |
  #!/bin/bash
  pip install psycopg2-binary trino sqlalchemy-trino

configOverrides:
  secret: |
    import os
    SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY")
    SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")

init:
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@superset.local
    password: admin1234567890

supersetWorker:
  enabled: false

supersetCeleryBeat:
  enabled: false

supersetCeleryFlower:
  enabled: false
