image:
  repository: docker.io/apache/superset
  tag: "4.1.0"

service:
  type: ClusterIP

ingress:
  enabled: false

postgresql:
  enabled: false

secretEnv:
  create: false

envFromSecret: superset-env

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: nfs-storage
      size: 2Gi

bootstrapScript: |
  #!/bin/bash
  pip install psycopg2-binary trino sqlalchemy-trino

configOverrides:
  secret: |
    import os
    SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY")
    SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")

init:
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@superset.local
    password: admin1234567890

supersetWorker:
  enabled: true

supersetCeleryBeat:
  enabled: false

supersetCeleryFlower:
  enabled: false
