apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: grafana
spec:
  config:
    server:
      root_url: https://grafana-monitoring.apps.ocp4.infrahub.com
    security:
      admin_user: admin
      admin_password: admin1234567890
    auth:
      disable_login_form: "false"
    auth.generic_oauth:
      enabled: "true"
      name: Keycloak
      allow_sign_up: "true"
      client_id: grafana
      client_secret: zCK9pIZmQHDy84Shkg3s8RfELS9aLNUn
      scopes: openid email profile
      auth_url: https://keycloak.apps.ocp4.infrahub.com/realms/infrahub/protocol/openid-connect/auth
      token_url: http://keycloak-service.keycloak.svc.cluster.local:8080/realms/infrahub/protocol/openid-connect/token
      api_url: http://keycloak-service.keycloak.svc.cluster.local:8080/realms/infrahub/protocol/openid-connect/userinfo
      tls_skip_verify_insecure: "true"
      role_attribute_path: "contains(roles[*], 'admin') && 'Admin' || 'Viewer'"
    log:
      mode: console
  deployment:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: worker2.ocp4.infrahub.com
          containers:
            - name: grafana
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                  ephemeral-storage: 200Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
                  ephemeral-storage: 500Mi
