apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: monitoring
type: Opaque
stringData:
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkxBVlprQWlhVlpCdDE3b09CMFRNc0prRVRZM19PNmY5TUhUMHhqbFVQaVEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MjA5MjA0NDg0NywiaWF0IjoxNzc2Njg0ODQ3LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiI4YmMwZjY0YS03Yzg2LTRkZTEtYWRlNC0wMDljM2NmN2U4NjYiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im1vbml0b3JpbmciLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ3JhZmFuYS1zYSIsInVpZCI6IjNlZjUyMWJmLTgzN2QtNDAyZi04NmU2LWMwOWNjOWExZjgxOSJ9fSwibmJmIjoxNzc2Njg0ODQ3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bW9uaXRvcmluZzpncmFmYW5hLXNhIn0.WfbZ5X1-37tHgM8zHrbNn_rreioDQZ3IZinu-kA9dmTz81gOXEHcxNT6z8TP4Y08SpxpmQFOn6_fyv0DfwWY2OsvAFi4wfwhI5OEo6MHyiZZ93aEXMhVNMtB0QB_z_PWu8Sy9LGY9b2wU4peprcpBY5oXFF7_aEN9j8tbjckK2Ffdh7djWZigHy4UM9tJ0Wn8On1RXlzH82av9PGnqq67S_gXlDqhAeKr9FHHoLwN18t5vIhOe-ifGst7_mO50izMZMgerudbSXHKwXcm2aZuHwVXSQnR8qGhEK2B4EHfpmfB08azOGoeF0bCGxpBV36qHQ1Gbm9hL1BesHApcNdUlE1oNC4EonI90EKTM1DzbOnxNWWmGmFzzz1XdIzyfUn0Q9cnrfQ1trgqZ9S-p9mlQFzWfB-_C2ZCkZXy01YCCcWuawCN8o-Bw2sUm-LekmAqLva8XPoqAinZ8aQoVhdOjWLF5KiMQ2J50E3L739efjY7NC9lEi00wP-55WtZagbzNBo_ND1P9HMSA2kLvgt_-kVTtmVWfiu2cGh6J8-XGfPRKonS4gcDdF1T44Lkl3wS_-UbdGeFFuWdkxKx7TZrtWaRusAbV1ZvWmhTcNyENaj7ABNCqgESeRBK6ZMX8w-0sVT74ckJUBwVGLXPc6hQTOH9Zh1vCQVFg-9dYJ3ozs
