apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  namespaceSelector:
    matchNames:
      - minio
  endpoints:
    - port: http
      path: /minio/health/live
      interval: 30s
