apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: lakehouse
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: nifi
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: governance
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: superset
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    project: sovereign-data-platform
    argocd.argoproj.io/managed-by: openshift-gitops
