apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-nodepool
  namespace: kafka
  labels:
    strimzi.io/cluster: lakehouse-kafka
spec:
  replicas: 3
  roles: 
    - broker
    - controller
  storage:
    type: persistent-claim
    size: 10Gi
    storageClassName: nfs-storage

