apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.1.0
  replicas: 1
  bootstrapServers: lakehouse-kafka-kafka-bootstrap:9092
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/kafka/kafka-connect-s3:latest
    plugins:
      - name: kafka-connect-s3
        artifacts:
          - type: zip
            url: http://172.24.66.231:9191/aiven-s3.zip
  config:
    group.id: kafka-connect-group
    offset.storage.topic: kafka-connect-offsets
    config.storage.topic: kafka-connect-configs
    status.storage.topic: kafka-connect-status
