apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: download-postgres-driver
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              curl -L https://jdbc.postgresql.org/download/postgresql-42.7.3.jar \
              -o /opt/hive/lib/ext/postgresql-42.7.3.jar
          volumeMounts:
            - name: hive-lib
              mountPath: /opt/hive/lib/ext
      containers:
        - name: hive-metastore
          image: apache/hive:standalone-metastore-4.1.0
          ports:
            - containerPort: 9083
          env:
            - name: DB_DRIVER
              value: postgres
          volumeMounts:
            - name: config
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: hive-lib
              mountPath: /opt/hive/lib/ext
      volumes:
        - name: config
          configMap:
            name: hive-metastore-config
        - name: hive-lib
          emptyDir: {}
