---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-secret
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: platform/minio
  refreshAfter: 30s
  destination:
    name: minio
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgresql-secret
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: platform/postgresql
  refreshAfter: 30s
  destination:
    name: postgresql
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nifi-secret
  namespace: nifi
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: platform/nifi
  refreshAfter: 30s
  destination:
    name: nifi-credentials
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: superset-secret
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: platform/superset
  refreshAfter: 30s
  destination:
    name: superset-env
    create: true
    overwrite: true
