apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-data
  namespace: nifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
