apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-airflow-scheduler-0
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 100Gi
