apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: openshift-gitops
spec:
  project: default

  ignoreDifferences:
    - group: batch
      kind: Job
    - group: ""
      kind: Secret
      name: airflow-jwt-secret
    - group: ""
      kind: Secret
      name: airflow-metadata

  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: 1.20.0
    helm:
      valuesObject:
        executor: LocalExecutor

        rbac:
          create: true
          createSCCRoleBinding: true

        postgresql:
          enabled: false

        redis:
          enabled: false

        data:
          metadataConnection:
            user: hive
            pass: hive123
            protocol: postgresql
            host: postgresql.postgresql.svc.cluster.local
            port: 5432
            db: airflow

        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false

        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false

        dags:
          persistence:
            enabled: false

        logs:
          persistence:
            enabled: false

        triggerer:
          enabled: false

        flower:
          enabled: false

        webserver:
          service:
            type: ClusterIP

        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
