apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.20.0
      helm:
        valueFiles:
          - $values/platform/airflow/values.yaml
    - repoURL: https://github.com/bakralakhras/OpenShift-ArgoCD.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
