apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: openshift-gitops
  labels:
    project: sovereign-data-platform
spec:
  project: default
  source:
    repoURL: https://github.com/bakralakhras/OpenShift-ArgoCD.git
    targetRevision: HEAD
    path: platform/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
