apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      valuesObject:
        nfs:
          server: 172.24.66.228
          path: /data/nfs-ocp
        storageClass:
          name: nfs-storage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

