apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/bakralakhras/OpenShift-ArgoCD.git
    targetRevision: HEAD
    path: platform/nifi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
