apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/bakralakhras/OpenShift-ArgoCD.git
    targetRevision: HEAD
    path: platform/vault-config
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
