apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-monitoring
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/bakralakhras/OpenShift-ArgoCD.git
    targetRevision: HEAD
    path: platform/vault-monitoring
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
