apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
  labels:
    app: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: trino
          image: trinodb/trino:435
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: config
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: config
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: config
              mountPath: /etc/trino/catalog/iceberg.properties
              subPath: iceberg.properties
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1"
      volumes:
        - name: config
          configMap:
            name: trino-config
