apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trino
  namespace: trino
  labels:
    app: trino
spec:
  selector:
    matchLabels:
      app: trino
  endpoints:
    - port: http
      path: /v1/info
      interval: 30s
